#!/usr/bin/env python3
"""Publish the canonical rich Memento demo to one shared web runtime.

The product guide embeds ``docs/demo/dashboard.html`` and the independent demo
opens the same URL. The Chrome preview package is also assembled from these
generated bytes, so there is no second hand-maintained demo implementation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "chrome-newtab"
OUTPUT_DIR = ROOT / "docs" / "demo"
LEGACY_OUTPUT = ROOT / "docs" / "Memento-Cognitive-Home-Standalone.html"

RUNTIME_FILES = (
    "manifest.json",
    "dashboard.html",
    "dashboard.css",
    "dashboard.js",
    "cognitive-demo-fixture.js",
    "photo-cache-library.js",
    "photo-library.js",
    "daily-summary-library.js",
    "directory-access-library.js",
    "dashboard-cache-library.js",
    "dashboard-operations-library.js",
    "context-agent-library.js",
    "remember-agent-v1-library.js",
    "cognitive-home-library.js",
    "prompts.js",
    "viewer.html",
    "viewer.js",
    "archive-sanitizer-library.js",
    "README-DEMO.md",
)


def source_digest() -> str:
    digest = hashlib.sha256()
    for name in RUNTIME_FILES:
        path = SOURCE_DIR / name
        if not path.is_file():
            raise FileNotFoundError(f"missing canonical demo dependency: {name}")
        digest.update(name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def legacy_redirect(version: str, digest: str) -> bytes:
    html = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="memento-shared-demo-version" content="{version}">
  <meta name="memento-source-sha256" content="{digest}">
  <meta http-equiv="refresh" content="0; url=demo/dashboard.html">
  <link rel="canonical" href="demo/dashboard.html">
  <title>Memento · 打开认知主页 Demo</title>
</head>
<body>
  <p><a href="demo/dashboard.html">打开 Memento 认知主页 Demo</a></p>
  <script>location.replace('demo/dashboard.html' + location.search + location.hash);</script>
</body>
</html>
"""
    return html.encode("utf-8")


def expected_outputs() -> dict[Path, bytes]:
    manifest = json.loads((SOURCE_DIR / "manifest.json").read_text(encoding="utf-8"))
    digest = source_digest()
    outputs = {OUTPUT_DIR / name: (SOURCE_DIR / name).read_bytes() for name in RUNTIME_FILES}
    outputs[OUTPUT_DIR / "runtime.json"] = (
        json.dumps(
            {
                "version": manifest["version"],
                "source": "chrome-newtab",
                "source_sha256": digest,
                "entrypoint": "dashboard.html",
                "files": list(RUNTIME_FILES),
            },
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n"
    ).encode("utf-8")
    outputs[LEGACY_OUTPUT] = legacy_redirect(manifest["version"], digest)
    return outputs


def check(outputs: dict[Path, bytes]) -> int:
    stale = [path for path, expected in outputs.items() if not path.is_file() or path.read_bytes() != expected]
    expected_names = {path.name for path in outputs if path.parent == OUTPUT_DIR}
    unexpected = []
    if OUTPUT_DIR.is_dir():
        unexpected = [path for path in OUTPUT_DIR.iterdir() if path.is_file() and path.name not in expected_names]
    if stale or unexpected:
        for path in stale:
            print(f"shared demo output is stale: {path}")
        for path in unexpected:
            print(f"shared demo output is unexpected: {path}")
        return 1
    print(f"shared demo runtime is current: {OUTPUT_DIR}")
    return 0


def write(outputs: dict[Path, bytes]) -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    expected_names = {path.name for path in outputs if path.parent == OUTPUT_DIR}
    for path in OUTPUT_DIR.iterdir():
        if path.is_file() and path.name not in expected_names:
            path.unlink()
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    print(f"published shared demo runtime: {OUTPUT_DIR}")
    print(f"kept legacy redirect: {LEGACY_OUTPUT}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = expected_outputs()
    return check(outputs) if args.check else write(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
